// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.Bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.Bank;

public interface BankManager extends Ice.Object,
                                     _BankManagerOperations, _BankManagerOperationsNC
{
    public static final long serialVersionUID = -937001586L;
}
