// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.Bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.Bank;

public class IncorrectAmount extends Ice.UserException
{
    public IncorrectAmount()
    {
    }

    public IncorrectAmount(Throwable __cause)
    {
        super(__cause);
    }

    public String
    ice_name()
    {
        return "server.Bank::IncorrectAmount";
    }

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::server.Bank::IncorrectAmount", -1, true);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = -1602432140L;
}
